### ISSUE TITLE
FreeBSD, mach

### ISSUE THREAD

**Issue by abishai** [evilsocket/gibson#16]
```
#elif defined(HAVE_TASKINFO)
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/sysctl.h>
#include <mach/task.h>
#include <mach/mach_init.h>
```

AFAIK, mach vm is not used in modern FreeBSD at all.
Can't we use native FreeBSD functions like kvm_getprocs to get RSS ?

**Comment by evilsocket** [comment]
the HAVE_TASKINFO section should be compatible with every _bsd, are kvm__ functions available on every bsd version ?

**Comment by abishai** [comment]
According mans - yes.
Are you sure mach headers are the part of FreeBSD ? I have userland and kernel sources on my system and found no trace of them.

**Comment by evilsocket** [comment]
oh my God my bad! there was an error in the configure.h.in file ... you are 100% right, HAVE_TASKINFO should be defined only on Mac. Committed a patch right now, i suggest to delete the repo and clone it again since cmake has its own cache
