### ISSUE TITLE
[FEATURE-REQUEST] optional argument: *max_items*  for ``mget`` command

### ISSUE THREAD

**Issue by jettify** [evilsocket/gibson#21]
Hi, Simone!
Interesting usecase for `gibson` is autocomplete, since we can query values by key _prefix_, but it would be really nice to have something like _LIMIT_ from SQL databases, so in case of short _prefix_, we would not fetch whole _trie_ from db. 

Command syntax can be:

```
MGET <prefix> <max_items>
```

where _max_items_, optional argument.

PS: I'am working on https://github.com/jettify/aiogibson , async python3 client

**Comment by evilsocket** [comment]
Hi there and sorry for the late reply, I wasn't @ home for the last 10 days :)
This is an interesting feature to add, I will work on it as soon as I will get some free time! :)

**Comment by evilsocket** [comment]
Hi @jettify I hope you're still there XD Anyway, I've implemented this feature inside the mget_limit branch, soon I'll merge it into the master and release a new version of Gibson.

**Comment by evilsocket** [comment]
Done, you can now use the [1.1.0](https://github.com/evilsocket/gibson/releases/tag/1.1.0) release.

**Comment by jettify** [comment]
Thank you! I've already tested this feature)

**Comment by evilsocket** [comment]
:+1:
