### ISSUE TITLE
Misuse of the BSD license

### ISSUE THREAD

**Issue by antirez** [evilsocket/gibson#22]
Hello Simone, how are you?

I noticed Gibson includes parts of the Redis source code, however original copyright notices are gone.
I enjoy Redis code was useful in order to create a different caching server: we need diversity! And I release stuff BSD licensed exactly because I like and hope other people reuse it.

However please follow the obligations of the license and re-add back the original copyright notices in every file that contains code from Redis: credit is due :-) Copyright is not like licenses. With BSD I give you a set of freedoms to reuse my code, but this does not mean the copyright was transferred to you. By removing the original copyright notice and adding your instead of the original one, you are basically claiming copyright.

Of course you should add your copyright (without removing the original one) every time you add something to the same file. However not if the modification is removing functions you don't need.

Thanks,
Salvatore

**Comment by antirez** [comment]
Just to clarify what is the right way to do this, files containing Redis code should have a copyright like that, assuming they contain also your changes:

```
 * Copyright (c) 2009-2013, Salvatore Sanfilippo <antirez at gmail dot com>
 * Copyright (c) 2013, Simone Margaritelli <evilsocket at gmail dot com>
```

And assuming the Redis file had no other contributors, otherwise all need to be listed.
Dates are just an example.

Another way to do this in the right way is to, also, even in a latter part of the file, include the full license with the original copyright.

Like

```
/* .... your copyright / license ...
 *
 * Original copyright and license:
 *
 * Copyright (c) 2009-2013, Salvatore Sanfilippo <antirez at gmail dot com>
 * ... */
```

**Comment by evilsocket** [comment]
my bad, will fix this asap

**Comment by antirez** [comment]
Thanks Simone, almost right... ;-) Dates were examples, so `2009-2013` should be replaced with the copyright notice you saw in the original Redis files your implementation uses. Thanks for the so fast reply to the issue!

**Comment by evilsocket** [comment]
Ops sorry I assumed you already wrote correct dates, since I don't honestly remember which specific version I used, can I put current files dates?

**Comment by antirez** [comment]
@evilsocket sure, everywhere you see < 2014, it is probably just me failing to update my own copyright dates...

**Comment by evilsocket** [comment]
would 2009-2015 be ok? :)

**Comment by antirez** [comment]
I suggest using 2006 as starting date into net.c since ae.c from Redis is 2006. zmalloc.c is fine with 2009.   Endianess functions are from 2011.

**Comment by evilsocket** [comment]
Fair enough, just gimme 1 minute since I'm currently working on another branch ;)

**Comment by antirez** [comment]
N.b. this is all about _form_ in the way the code is used. As long as copyright is retained, please feel free to use the Redis source code at your wish ;-)

**Comment by evilsocket** [comment]
This should do the trick a8feadc850044dfc1d02223c1bab8c2e0f89a3ee

**Comment by antirez** [comment]
Thank you

**Comment by evilsocket** [comment]
Thanks to YOU to have developed such a beautiful piece of code, I love the abstraction behind ae even if it's C code.

**Comment by antirez** [comment]
Thanks Simone :-)
