### ISSUE TITLE
Install gibson binaries into /usr/bin instead of /usr/sbin

### ISSUE THREAD

**Issue by anatol** [evilsocket/gibson#6]
Hi, I am trying to add this software into Arch Linux.

There is a lot of confusion about /bin /usr/bin /usr/sbin and most users include all of the paths into PATH. It is not a surprise that different distros try to merge these directories. Examples are Fedora Arch and probably so other.

The Arch recommendation is not to use /usr/sbin but use /usr/bin instead.

**Comment by evilsocket** [comment]
Fixed, tnx :)
