### ISSUE TITLE
Position of <TTL> in SET command

### ISSUE THREAD

**Issue by dck** [evilsocket/gibson#7]
Hello. Could i ask why ttl is on second position in set command?
In my opinion SET command is often used without ttl. 
Nevertheless TTL as the last and  optional parameter would be friendlier and clearer
    `SET <key> <value> [TTL]`
And  TTL is 0 by default, of course.
What do you think about it?

**Comment by evilsocket** [comment]
You are talking about the console client i guess :)
While i was developing it, i preferred to keep arguments in the same order of the protocol itself ( OP_SET <ttl> <key> <value> ) and with the same mandatory logic ( actually the ttl IS a mandatory argument in the protocol itself ).
Instead in the client libraries ( the PHP5 extension and the Node.js one which is being developed ) the ttl, being optional ( but at lower level always set to 0 if not specified ) its implemented as the last parameter.

So, do you think that in the console client the the ttl should be the last and optional parameter for the set operator ?

**Comment by evilsocket** [comment]
Closing, but feel free to comment if you think the topic should be discussed anymore.
